import { useMemo } from 'react';
import { useFilterRulesEditorProps } from './useFilterRulesEditorProps';

type FilterRulesEditorOptions = Parameters<typeof useFilterRulesEditorProps>[0];

export function useFilterRulesEditorOptions({
  effectiveFilterRules,
  filterGroupNameInput,
  filterRuleDragState,
  filterRules,
  filterToggleLabel,
  handleDeleteFilterRuleGroup,
  handleExportFilterRuleGroups,
  handleImportFilterRuleGroups,
  handleSaveFilterRuleGroup,
  hasAnyConfiguredFilterRule,
  messages,
  normalizedFilterRuleGroups,
  onAddFilterRule,
  onFilterGroupNameInputChange,
  onKeywordKeyDown,
  onLoadFilterRuleGroup,
  onMoveFilterRule,
  onRemoveFilterRule,
  onRuleDragEnd,
  onRuleDragOver,
  onRuleDragStart,
  onRuleDrop,
  onSelectedFilterGroupChange,
  onToggleResultPanelAndRefresh,
  onUpdateFilterRule,
  onClearFilterRules,
  selectedFilterGroupName,
  setFilterGroupNameInput,
}: FilterRulesEditorOptions): FilterRulesEditorOptions {
  return useMemo(
    () => ({
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      handleDeleteFilterRuleGroup,
      handleExportFilterRuleGroups,
      handleImportFilterRuleGroups,
      handleSaveFilterRuleGroup,
      hasAnyConfiguredFilterRule,
      messages,
      normalizedFilterRuleGroups,
      onAddFilterRule,
      onFilterGroupNameInputChange,
      onKeywordKeyDown,
      onLoadFilterRuleGroup,
      onMoveFilterRule,
      onRemoveFilterRule,
      onRuleDragEnd,
      onRuleDragOver,
      onRuleDragStart,
      onRuleDrop,
      onSelectedFilterGroupChange,
      onToggleResultPanelAndRefresh,
      onUpdateFilterRule,
      onClearFilterRules,
      selectedFilterGroupName,
      setFilterGroupNameInput,
    }),
    [
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      handleDeleteFilterRuleGroup,
      handleExportFilterRuleGroups,
      handleImportFilterRuleGroups,
      handleSaveFilterRuleGroup,
      hasAnyConfiguredFilterRule,
      messages,
      normalizedFilterRuleGroups,
      onAddFilterRule,
      onFilterGroupNameInputChange,
      onKeywordKeyDown,
      onLoadFilterRuleGroup,
      onMoveFilterRule,
      onRemoveFilterRule,
      onRuleDragEnd,
      onRuleDragOver,
      onRuleDragStart,
      onRuleDrop,
      onSelectedFilterGroupChange,
      onToggleResultPanelAndRefresh,
      onUpdateFilterRule,
      onClearFilterRules,
      selectedFilterGroupName,
      setFilterGroupNameInput,
    ]
  );
}