import { useMemo } from 'react';
import { useSearchQuerySectionProps } from './useSearchQuerySectionProps';

type SearchQueryOptions = Omit<Parameters<typeof useSearchQuerySectionProps>[0], 'canReplace'>;

export function useSearchQueryOptions({
  caseSensitive,
  handleKeywordKeyDown,
  handleReplaceAll,
  handleReplaceCurrent,
  isReplaceMode,
  keyword,
  messages,
  navigateByStep,
  parseEscapeSequences,
  recentReplaceValues,
  recentSearchKeywords,
  replaceValue,
  resetSearchState,
  resultToggleTitle,
  reverseSearch,
  searchInputRef,
  searchMode,
  setCaseSensitive,
  setErrorMessage,
  setFeedbackMessage,
  setKeyword,
  setParseEscapeSequences,
  setReplaceValue,
  setReverseSearch,
  setSearchMode,
  toggleResultPanelAndRefresh,
}: SearchQueryOptions): SearchQueryOptions {
  return useMemo(
    () => ({
      caseSensitive,
      handleKeywordKeyDown,
      handleReplaceAll,
      handleReplaceCurrent,
      isReplaceMode,
      keyword,
      messages,
      navigateByStep,
      parseEscapeSequences,
      recentReplaceValues,
      recentSearchKeywords,
      replaceValue,
      resetSearchState,
      resultToggleTitle,
      reverseSearch,
      searchInputRef,
      searchMode,
      setCaseSensitive,
      setErrorMessage,
      setFeedbackMessage,
      setKeyword,
      setParseEscapeSequences,
      setReplaceValue,
      setReverseSearch,
      setSearchMode,
      toggleResultPanelAndRefresh,
    }),
    [
      caseSensitive,
      handleKeywordKeyDown,
      handleReplaceAll,
      handleReplaceCurrent,
      isReplaceMode,
      keyword,
      messages,
      navigateByStep,
      parseEscapeSequences,
      recentReplaceValues,
      recentSearchKeywords,
      replaceValue,
      resetSearchState,
      resultToggleTitle,
      reverseSearch,
      searchInputRef,
      searchMode,
      setCaseSensitive,
      setErrorMessage,
      setFeedbackMessage,
      setKeyword,
      setParseEscapeSequences,
      setReplaceValue,
      setReverseSearch,
      setSearchMode,
      toggleResultPanelAndRefresh,
    ]
  );
}