// @ts-nocheck
import { EditorContextMenu } from './EditorContextMenu';
import { EditorBase64DecodeToast } from './EditorBase64DecodeToast';
import { EditorBackdropLayer } from './EditorBackdropLayer';
import { EditorInputLayer } from './EditorInputLayer';
import { EditorLineNumberGutter } from './EditorLineNumberGutter';

export function EditorView({
  containerRef,
  activeSyntaxKey,
  isHugeEditableMode,
  contentRef,
  scrollContainerRef,
  contentViewportLeftPx,
  contentViewportWidth,
  horizontalOverflowMode,
  handleScroll,
  handleHugeScrollablePointerDown,
  tab,
  itemSize,
  wordWrap,
  hugeScrollableContentWidth,
  hugeEditablePaddingTop,
  hugeEditableSegmentHeightPx,
  settings,
  renderedFontSizePx,
  lineHeightPx,
  tabSize,
  contentTextPadding,
  contentTextRightPadding,
  contentBottomSafetyPadding,
  handleInput,
  handleEditableKeyDown,
  handleEditorPointerDown,
  handleEditorPointerMove,
  handleEditorPointerLeave,
  syncSelectionAfterInteraction,
  handleEditorContextMenu,
  handleCompositionStart,
  handleCompositionEnd,
  width,
  height,
  listRef,
  getListItemSize,
  onItemsRendered,
  editableSegment,
  usePlainLineRendering,
  plainStartLine,
  startLine,
  tokenFallbackPlainLines,
  tokenFallbackPlainStartLine,
  lineTokens,
  editableSegmentLines,
  plainLines,
  measureRenderedLineHeight,
  diffHighlightLineSet,
  unsavedChangeLineSet,
  outlineFlashLine,
  lineNumberMultiSelectionSet,
  highlightCurrentLine,
  activeLineNumber,
  renderHighlightedPlainLine,
  renderHighlightedTokens,
  showLineNumbers,
  lineNumberColumnWidthPx,
  lineNumberVirtualItemCount,
  lineNumberFontSizePx,
  lineNumberListRef,
  bookmarks,
  getLineNumberListItemSize,
  getLineNumberFromGutterElement,
  handleLineNumberWheel,
  handleLineNumberDoubleClick,
  handleLineNumberClick,
  handleLineNumberContextMenu,
  editorContextMenu,
  editorContextMenuRef,
  submenuPanelRefs,
  editSubmenuStyle,
  sortSubmenuStyle,
  convertSubmenuStyle,
  bookmarkSubmenuStyle,
  editSubmenuPositionClassName,
  sortSubmenuPositionClassName,
  convertSubmenuPositionClassName,
  bookmarkSubmenuPositionClassName,
  cleanupMenuItems,
  sortMenuItems,
  copyLabel,
  cutLabel,
  pasteLabel,
  deleteLabel,
  selectAllLabel,
  selectCurrentLineLabel,
  addCurrentLineToBookmarkLabel,
  editMenuLabel,
  sortMenuLabel,
  convertMenuLabel,
  convertBase64EncodeLabel,
  convertBase64DecodeLabel,
  copyBase64EncodeResultLabel,
  copyBase64DecodeResultLabel,
  bookmarkMenuLabel,
  addBookmarkLabel,
  removeBookmarkLabel,
  hasContextBookmark,
  handleSelectCurrentLineFromContext,
  handleAddCurrentLineBookmarkFromContext,
  handleEditorContextMenuAction,
  isEditorContextMenuActionDisabled,
  updateSubmenuVerticalAlignment,
  handleCleanupDocumentFromContext,
  handleConvertSelectionFromContext,
  handleAddBookmarkFromContext,
  handleRemoveBookmarkFromContext,
  showBase64DecodeErrorToast,
  base64DecodeFailedToastLabel,
}: any) {
  return (
    <div
      ref={containerRef}
      className={`flex-1 w-full h-full overflow-hidden bg-background relative editor-syntax-${activeSyntaxKey}`}
      tabIndex={-1}
    >
      <EditorInputLayer
        isHugeEditableMode={isHugeEditableMode}
        contentRef={contentRef}
        scrollContainerRef={scrollContainerRef}
        contentViewportLeftPx={contentViewportLeftPx}
        contentViewportWidth={contentViewportWidth}
        horizontalOverflowMode={horizontalOverflowMode}
        onScroll={handleScroll}
        onHugeScrollablePointerDown={handleHugeScrollablePointerDown}
        tabLineCount={tab.lineCount}
        itemSize={itemSize}
        wordWrap={wordWrap}
        hugeScrollableContentWidth={hugeScrollableContentWidth}
        hugeEditablePaddingTop={hugeEditablePaddingTop}
        hugeEditableSegmentHeightPx={hugeEditableSegmentHeightPx}
        fontFamily={settings.fontFamily}
        renderedFontSizePx={renderedFontSizePx}
        lineHeightPx={lineHeightPx}
        tabSize={tabSize}
        contentTextPadding={contentTextPadding}
        contentTextRightPadding={contentTextRightPadding}
        contentBottomSafetyPadding={contentBottomSafetyPadding}
        onInput={handleInput}
        onEditableKeyDown={handleEditableKeyDown}
        onEditorPointerDown={handleEditorPointerDown}
        onEditorPointerMove={handleEditorPointerMove}
        onEditorPointerLeave={handleEditorPointerLeave}
        onSyncSelectionAfterInteraction={syncSelectionAfterInteraction}
        onEditorContextMenu={handleEditorContextMenu}
        onCompositionStart={handleCompositionStart}
        onCompositionEnd={handleCompositionEnd}
      />

      <EditorBackdropLayer
        visible={true}
        width={width}
        height={height}
        contentViewportLeftPx={contentViewportLeftPx}
        contentViewportWidth={contentViewportWidth}
        contentBottomSafetyPadding={contentBottomSafetyPadding}
        tabLineCount={tab.lineCount}
        itemSize={itemSize}
        listRef={listRef}
        getListItemSize={getListItemSize}
        onItemsRendered={onItemsRendered}
        isHugeEditableMode={isHugeEditableMode}
        editableSegmentStartLine={editableSegment.startLine}
        usePlainLineRendering={usePlainLineRendering}
        plainStartLine={plainStartLine}
        startLine={startLine}
        tokenFallbackPlainLines={tokenFallbackPlainLines}
        tokenFallbackPlainStartLine={tokenFallbackPlainStartLine}
        lineTokens={lineTokens}
        editableSegmentLines={editableSegmentLines}
        plainLines={plainLines}
        measureRenderedLineHeight={measureRenderedLineHeight}
        wordWrap={wordWrap}
        contentTextPadding={contentTextPadding}
        contentTextRightPadding={contentTextRightPadding}
        fontFamily={settings.fontFamily}
        renderedFontSizePx={renderedFontSizePx}
        lineHeightPx={lineHeightPx}
        hugeScrollableContentWidth={hugeScrollableContentWidth}
        diffHighlightLineSet={diffHighlightLineSet}
        outlineFlashLine={outlineFlashLine}
        lineNumberMultiSelectionSet={lineNumberMultiSelectionSet}
        highlightCurrentLine={highlightCurrentLine}
        activeLineNumber={activeLineNumber}
        tabSize={tabSize}
        renderHighlightedPlainLine={renderHighlightedPlainLine}
        renderHighlightedTokens={renderHighlightedTokens}
      />

      <EditorLineNumberGutter
        visible={showLineNumbers}
        width={width}
        height={height}
        tabLineCount={tab.lineCount}
        lineNumberColumnWidthPx={lineNumberColumnWidthPx}
        lineNumberVirtualItemCount={lineNumberVirtualItemCount}
        itemSize={itemSize}
        lineHeightPx={lineHeightPx}
        lineNumberFontSizePx={lineNumberFontSizePx}
        fontFamily={settings.fontFamily}
        lineNumberListRef={lineNumberListRef}
        diffHighlightLineSet={diffHighlightLineSet}
        unsavedChangeLineSet={unsavedChangeLineSet}
        bookmarks={bookmarks}
        lineNumberMultiSelectionSet={lineNumberMultiSelectionSet}
        getLineNumberListItemSize={getLineNumberListItemSize}
        getLineNumberFromGutterElement={getLineNumberFromGutterElement}
        onLineNumberWheel={handleLineNumberWheel}
        onLineNumberDoubleClick={handleLineNumberDoubleClick}
        onLineNumberClick={handleLineNumberClick}
        onLineNumberContextMenu={handleLineNumberContextMenu}
      />

      <EditorContextMenu
        editorContextMenu={editorContextMenu}
        editorContextMenuRef={editorContextMenuRef}
        submenuPanelRefs={submenuPanelRefs}
        editSubmenuStyle={editSubmenuStyle}
        sortSubmenuStyle={sortSubmenuStyle}
        convertSubmenuStyle={convertSubmenuStyle}
        bookmarkSubmenuStyle={bookmarkSubmenuStyle}
        editSubmenuPositionClassName={editSubmenuPositionClassName}
        sortSubmenuPositionClassName={sortSubmenuPositionClassName}
        convertSubmenuPositionClassName={convertSubmenuPositionClassName}
        bookmarkSubmenuPositionClassName={bookmarkSubmenuPositionClassName}
        cleanupMenuItems={cleanupMenuItems}
        sortMenuItems={sortMenuItems}
        copyLabel={copyLabel}
        cutLabel={cutLabel}
        pasteLabel={pasteLabel}
        deleteLabel={deleteLabel}
        selectAllLabel={selectAllLabel}
        selectCurrentLineLabel={selectCurrentLineLabel}
        addCurrentLineToBookmarkLabel={addCurrentLineToBookmarkLabel}
        editMenuLabel={editMenuLabel}
        sortMenuLabel={sortMenuLabel}
        convertMenuLabel={convertMenuLabel}
        convertBase64EncodeLabel={convertBase64EncodeLabel}
        convertBase64DecodeLabel={convertBase64DecodeLabel}
        copyBase64EncodeResultLabel={copyBase64EncodeResultLabel}
        copyBase64DecodeResultLabel={copyBase64DecodeResultLabel}
        bookmarkMenuLabel={bookmarkMenuLabel}
        addBookmarkLabel={addBookmarkLabel}
        removeBookmarkLabel={removeBookmarkLabel}
        hasContextBookmark={hasContextBookmark}
        onSelectCurrentLine={handleSelectCurrentLineFromContext}
        onAddCurrentLineBookmark={handleAddCurrentLineBookmarkFromContext}
        onEditorAction={handleEditorContextMenuAction}
        isEditorActionDisabled={isEditorContextMenuActionDisabled}
        onUpdateSubmenuVerticalAlignment={updateSubmenuVerticalAlignment}
        onCleanup={handleCleanupDocumentFromContext}
        onConvert={handleConvertSelectionFromContext}
        onAddBookmark={handleAddBookmarkFromContext}
        onRemoveBookmark={handleRemoveBookmarkFromContext}
      />

      <EditorBase64DecodeToast
        visible={showBase64DecodeErrorToast}
        message={base64DecodeFailedToastLabel}
      />
    </div>
  );
}
