import {
  startTransition,
  useMemo,
  useRef,
} from 'react';
import type { FilterRulesEditorProps } from '@/components/search-panel/FilterRulesEditor';
import {
  SearchSidebarBody,
  SearchPanelOverlays,
  SearchSidebarChrome,
  useFilterRules,
  useSearchInput,
  useSearchPanelChrome,
  useSearchKeywordKeyDown,
  useSearchNavigation,
  useSearchResultFilterStepNavigation,
  useSearchReplaceHandlers,
  useSearchExecution,
  useSearchQuerySectionProps,
  useSearchResultPanel,
  useSearchSidebarFrame,
  useSearchPanelStore,
} from '@/components/search-panel';
export function SearchReplacePanel() {
  const {
    // Zustand selectors
    activeCursorPosition,
    activeTab,
    activeTabId,
    fontFamily,
    recentReplaceValues,
    recentSearchKeywords,
    setCursorPosition,
    updateSettings,
    updateTab,
    // Local state
    appliedResultFilterKeyword,
    caseSensitive,
    currentFilterMatchIndex,
    currentMatchIndex,
    errorMessage,
    feedbackMessage,
    filterMatches,
    isOpen,
    isResultFilterSearching,
    isSearching,
    keyword,
    matches,
    panelMode,
    parseEscapeSequences,
    replaceValue,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultPanelHeight,
    resultPanelState,
    reverseSearch,
    searchMode,
    searchSidebarWidth,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
    // Setters
    setAppliedResultFilterKeyword,
    setCaseSensitive,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterRuleGroups,
    setIsOpen,
    setIsResultFilterSearching,
    setIsSearching,
    setKeyword,
    setMatches,
    setPanelMode,
    setParseEscapeSequences,
    setReplaceValue,
    setResultFilterKeyword,
    setResultFilterStepLoadingDirection,
    setResultPanelHeight,
    setResultPanelState,
    setReverseSearch,
    setSearchMode,
    setSearchSidebarWidth,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    // Refs
    cachedFilterRef,
    cachedSearchRef,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    filterCountCacheRef,
    filterLineCursorRef,
    filterRunVersionRef,
    filterSessionIdRef,
    loadMoreDebounceRef,
    loadMoreLockRef,
    loadMoreSessionRef,
    minimizedResultWrapperRef,
    previousActiveTabIdRef,
    resultFilterStepRunVersionRef,
    resultListRef,
    resultPanelWrapperRef,
    runVersionRef,
    searchInputRef,
    searchSessionIdRef,
    sessionRestoreRunVersionRef,
    stopResultFilterSearchRef,
    tabSearchPanelStateRef,
    // Session lifecycle
    setFilterSessionId,
    setSearchSessionId,
    // UI derived
    inputContextCopyLabel,
    inputContextCutLabel,
    inputContextPasteLabel,
    isFilterMode,
    isReplaceMode,
    messages,
    normalizedFilterRuleGroups,
    resultListTextStyle,
    // Derived state
    backendResultFilterKeyword,
    effectiveSearchKeyword,
    isResultFilterActive,
    visibleCurrentFilterMatchIndex,
    visibleCurrentMatchIndex,
    visibleFilterMatches,
    visibleMatches,
    // Reset helpers
    resetFilterState,
    resetSearchState,
  } = useSearchPanelStore();

  const {
    getSearchSidebarOccludedRightPx,
    handleSearchUiBlurCapture,
    handleSearchUiFocusCapture,
    handleSearchUiPointerDownCapture,
    isSearchSidebarResizing,
    isSearchUiActive,
    searchSidebarContainerRef,
    startSearchSidebarResize,
  } = useSearchSidebarFrame({
    isOpen,
    searchSidebarWidth,
    setSearchSidebarWidth,
  });

  const {
    focusSearchInput,
    handleInputContextMenuAction,
    handleSearchSidebarContextMenu,
    inputContextMenu,
    inputContextMenuRef,
    rememberReplaceValue,
    rememberSearchKeyword,
  } = useSearchInput({
    isOpen,
    recentReplaceValues,
    recentSearchKeywords,
    searchInputRef,
    updateSettings,
  });

  const {
    addFilterRule,
    clearFilterRules,
    effectiveFilterRules,
    filterGroupNameInput,
    filterRuleDragState,
    filterRules,
    filterRulesKey,
    filterRulesPayload,
    handleDeleteFilterRuleGroup,
    handleExportFilterRuleGroups,
    handleImportFilterRuleGroups,
    handleLoadFilterRuleGroup,
    handleSaveFilterRuleGroup,
    handleSelectedFilterGroupChange,
    hasAnyConfiguredFilterRule,
    moveFilterRule,
    onFilterRuleDragEnd,
    onFilterRuleDragOver,
    onFilterRuleDragStart,
    onFilterRuleDrop,
    removeFilterRule,
    selectedFilterGroupName,
    setFilterGroupNameInput,
    updateFilterRule,
  } = useFilterRules({
    messages,
    normalizedFilterRuleGroups,
    resetFilterState,
    setErrorMessage,
    setFeedbackMessage,
    setFilterRuleGroups,
  });

  const {
    cancelPendingBatchLoad,
    executeFilter,
    executeFirstMatchSearch,
    executeSearch,
    loadMoreFilterMatches,
    loadMoreMatches,
    requestStopResultFilterSearch,
  } = useSearchExecution({
    activeTabId: activeTab?.id ?? null,
    appliedResultFilterKeyword,
    backendResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndex,
    currentMatchIndex,
    effectiveSearchKeyword,
    filterCountCacheRef,
    filterFailedLabel: messages.filterFailed,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterRulesPayload,
    filterRunVersionRef,
    filterSessionIdRef,
    isFilterMode,
    isOpen,
    keyword,
    loadMoreDebounceRef,
    loadMoreLockRef,
    loadMoreSessionRef,
    matches,
    panelMode,
    parseEscapeSequences,
    previousActiveTabIdRef,
    replaceValue,
    resetFilterState,
    resetSearchState,
    resultFilterKeyword,
    resultFilterStepRunVersionRef,
    resultPanelHeight,
    resultPanelState,
    reverseSearch,
    runVersionRef,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    searchSessionIdRef,
    searchSidebarWidth,
    sessionRestoreRunVersionRef,
    setAppliedResultFilterKeyword,
    setCaseSensitive,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsOpen,
    setIsResultFilterSearching,
    setIsSearching,
    setKeyword,
    setMatches,
    setPanelMode,
    setParseEscapeSequences,
    setReplaceValue,
    setResultFilterKeyword,
    setResultFilterStepLoadingDirection,
    setResultPanelHeight,
    setResultPanelState,
    setReverseSearch,
    setSearchMode,
    setSearchSessionId,
    setSearchSidebarWidth,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
    stopResultFilterSearchRef,
    tabSearchPanelStateRef,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
  });

  const hasMoreMatches = chunkCursorRef.current !== null;
  const hasMoreFilterMatches = filterLineCursorRef.current !== null;

  const {
    handleApplyResultFilter,
    handleSelectMatch,
    navigateByStep,
    navigateToMatch,
  } = useSearchNavigation({
    activeCursorPosition,
    activeTabId: activeTab?.id ?? null,
    appliedResultFilterKeyword,
    backendResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    cancelPendingBatchLoad,
    caseSensitive,
    chunkCursorRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    executeFilter,
    executeFirstMatchSearch,
    executeSearch,
    filterCountCacheRef,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterRulesPayload,
    filterFailedLabel: messages.filterFailed,
    getSearchSidebarOccludedRightPx,
    isFilterMode,
    isResultFilterSearching,
    keyword,
    loadMoreFilterMatches,
    loadMoreLockRef,
    loadMoreMatches,
    matches,
    nextMatchLabel: messages.nextMatch,
    prevMatchLabel: messages.prevMatch,
    rememberSearchKeyword,
    requestStopResultFilterSearch,
    resultFilterKeyword,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setAppliedResultFilterKeyword,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setCursorPosition,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsResultFilterSearching,
    setMatches,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    startTransition,
    stopResultFilterSearchRef,
  });

  const { handleReplaceAll, handleReplaceCurrent } = useSearchReplaceHandlers({
    activeTabId: activeTab?.id ?? null,
    activeTabLineCount: activeTab?.lineCount ?? null,
    backendResultFilterKeyword,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    executeSearch,
    keyword,
    navigateToMatch,
    noReplaceMatchesMessage: messages.noReplaceMatches,
    parseEscapeSequences,
    rememberReplaceValue,
    rememberSearchKeyword,
    replaceAllFailedLabel: messages.replaceAllFailed,
    replaceCurrentFeedback: messages.replacedCurrent,
    replaceFailedLabel: messages.replaceFailed,
    replacedAllFeedback: messages.replacedAll,
    replaceValue,
    searchMode,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setMatches,
    setSearchSessionId,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
    updateTab,
  });

  const handleKeywordKeyDown = useSearchKeywordKeyDown({
    executeFilter,
    executeSearch,
    isFilterMode,
    isSearching,
    keyword,
    navigateByStep,
    rememberSearchKeyword,
    reverseSearch,
    searchInputRef,
    setIsOpen,
    setResultPanelState,
  });


  const navigateResultFilterByStepRef = useRef<((step: number) => Promise<void>) | null>(null);

  const {
    copyPlainTextResultEntries,
    copyPlainTextResults,
    displayTotalFilterMatchedLineCount,
    displayTotalFilterMatchedLineCountText,
    displayTotalMatchCount,
    displayTotalMatchCountText,
    displayTotalMatchedLineCountText,
    filterToggleLabel,
    handleClearResultFilter,
    handleCloseResultPanel,
    handleRefreshResults,
    handleReopenResultPanel,
    handleResultFilterAction,
    handleResultFilterNext,
    handleResultFilterPrev,
    handleResultListScroll,
    handleResultPanelResizeMouseDown,
    hasAppliedResultFilterKeyword,
    plainTextResultEntries,
    resultToggleTitle,
    scrollResultItemIntoView,
    toggleResultPanelAndRefresh,
  } = useSearchResultPanel({
    cancelPendingBatchLoad,
    executeFilter,
    executeSearch,
    filterMatchesLength: filterMatches.length,
    filterRulesPayloadLength: filterRulesPayload.length,
    hasMoreFilterMatches,
    hasMoreMatches,
    isFilterMode,
    isOpen,
    isResultFilterSearching,
    isSearching,
    keyword,
    loadMoreDebounceRef,
    loadMoreFilterMatches,
    loadMoreLockRef,
    loadMoreMatches,
    matchesLength: matches.length,
    messages,
    navigateResultFilterByStepRef,
    onApplyResultFilter: handleApplyResultFilter,
    rememberSearchKeyword,
    requestStopResultFilterSearch,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultListRef,
    resultPanelHeight,
    resultPanelState,
    setAppliedResultFilterKeyword,
    setErrorMessage,
    setFeedbackMessage,
    setResultFilterKeyword,
    setResultPanelHeight,
    setResultPanelState,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
    visibleFilterMatches,
    visibleMatches,
  });

  const navigateResultFilterByStep = useSearchResultFilterStepNavigation({
    activeTabId: activeTab?.id ?? null,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    filterCountCacheRef,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterRulesPayload,
    isFilterMode,
    isResultFilterSearching,
    isSearching,
    keyword,
    loadMoreLockRef,
    matches,
    parseEscapeSequences,
    resultFilterKeyword,
    resultFilterStepNoMatch: messages.resultFilterStepNoMatch,
    resultFilterStepRunVersionRef,
    scrollResultItemIntoView,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsSearching,
    setMatches,
    setResultFilterStepLoadingDirection,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
  });

  navigateResultFilterByStepRef.current = navigateResultFilterByStep;

  const filterRulesEditorProps = useMemo<FilterRulesEditorProps>(
    () => ({
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      hasAnyConfiguredFilterRule,
      messages,
      normalizedFilterRuleGroups,
      selectedFilterGroupName,
      onAddFilterRule: addFilterRule,
      onClearFilterGroupNameInput: () => setFilterGroupNameInput(''),
      onClearFilterRules: clearFilterRules,
      onDeleteFilterRuleGroup: () => void handleDeleteFilterRuleGroup(),
      onExportFilterRuleGroups: () => void handleExportFilterRuleGroups(),
      onFilterGroupNameInputChange: setFilterGroupNameInput,
      onImportFilterRuleGroups: () => void handleImportFilterRuleGroups(),
      onKeywordKeyDown: handleKeywordKeyDown,
      onLoadFilterRuleGroup: handleLoadFilterRuleGroup,
      onMoveFilterRule: moveFilterRule,
      onRemoveFilterRule: removeFilterRule,
      onRuleDragEnd: onFilterRuleDragEnd,
      onRuleDragOver: onFilterRuleDragOver,
      onRuleDragStart: onFilterRuleDragStart,
      onRuleDrop: onFilterRuleDrop,
      onSaveFilterRuleGroup: () => void handleSaveFilterRuleGroup(),
      onSelectedFilterGroupChange: handleSelectedFilterGroupChange,
      onToggleResultPanelAndRefresh: toggleResultPanelAndRefresh,
      onUpdateFilterRule: updateFilterRule,
    }),
    [
      addFilterRule,
      clearFilterRules,
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      handleDeleteFilterRuleGroup,
      handleExportFilterRuleGroups,
      handleImportFilterRuleGroups,
      handleKeywordKeyDown,
      handleLoadFilterRuleGroup,
      handleSaveFilterRuleGroup,
      handleSelectedFilterGroupChange,
      hasAnyConfiguredFilterRule,
      messages,
      moveFilterRule,
      normalizedFilterRuleGroups,
      onFilterRuleDragEnd,
      onFilterRuleDragOver,
      onFilterRuleDragStart,
      onFilterRuleDrop,
      removeFilterRule,
      selectedFilterGroupName,
      setFilterGroupNameInput,
      toggleResultPanelAndRefresh,
      updateFilterRule,
    ]
  );

  const searchQuerySectionProps = useSearchQuerySectionProps({
    canReplace: !!activeTab,
    caseSensitive,
    handleKeywordKeyDown,
    handleReplaceAll,
    handleReplaceCurrent,
    isReplaceMode,
    keyword,
    messages,
    navigateByStep,
    parseEscapeSequences,
    recentReplaceValues,
    recentSearchKeywords,
    replaceValue,
    resetSearchState,
    resultToggleTitle,
    reverseSearch,
    searchInputRef,
    searchMode,
    setCaseSensitive,
    setErrorMessage,
    setFeedbackMessage,
    setKeyword,
    setParseEscapeSequences,
    setReplaceValue,
    setReverseSearch,
    setSearchMode,
    toggleResultPanelAndRefresh,
  });

  const {
    searchPanelOverlaysProps,
    searchSidebarBodyProps,
    searchSidebarChromeProps,
  } = useSearchPanelChrome({
    handleSearchUiBlurCapture,
    handleSearchUiFocusCapture,
    handleSearchUiPointerDownCapture,
    isSearchSidebarResizing,
    isSearchUiActive,
    searchSidebarContainerRef,
    startSearchSidebarResize,
    activeTabId,
    currentFilterMatchIndex,
    currentMatchIndex,
    effectiveFilterRulesLength: effectiveFilterRules.length,
    errorMessage,
    feedbackMessage,
    filterMatches,
    filterRulesPayloadLength: filterRulesPayload.length,
    fontFamily,
    hasActiveTab: !!activeTab,
    hasMoreFilterMatches,
    hasMoreMatches,
    isFilterMode,
    isOpen,
    isResultFilterActive,
    isResultFilterSearching,
    isSearching,
    keyword,
    matches,
    messages,
    minimizedResultWrapperRef,
    panelMode,
    previousActiveTabIdRef,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultListRef,
    resultListTextStyle,
    resultPanelHeight,
    resultPanelState,
    resultPanelWrapperRef,
    reverseSearch,
    searchSidebarWidth,
    stopResultFilterSearchRef,
    visibleCurrentFilterMatchIndex,
    visibleCurrentMatchIndex,
    visibleFilterMatches,
    visibleMatches,
    setAppliedResultFilterKeyword,
    setErrorMessage,
    setFeedbackMessage,
    setIsOpen,
    setIsResultFilterSearching,
    setPanelMode,
    setResultFilterKeyword,
    setResultPanelState,
    filterRulesEditorProps,
    searchQuerySectionProps,
    focusSearchInput,
    handleInputContextMenuAction,
    handleSearchSidebarContextMenu,
    inputContextCopyLabel,
    inputContextCutLabel,
    inputContextMenu,
    inputContextMenuRef,
    inputContextPasteLabel,
    copyPlainTextResultEntries,
    copyPlainTextResults,
    displayTotalFilterMatchedLineCount,
    displayTotalFilterMatchedLineCountText,
    displayTotalMatchCount,
    displayTotalMatchCountText,
    displayTotalMatchedLineCountText,
    handleClearResultFilter,
    handleCloseResultPanel,
    handleRefreshResults,
    handleReopenResultPanel,
    handleResultFilterAction,
    handleResultFilterNext,
    handleResultFilterPrev,
    handleResultListScroll,
    handleResultPanelResizeMouseDown,
    hasAppliedResultFilterKeyword,
    plainTextResultEntryCount: plainTextResultEntries.length,
    handleSelectMatch,
    navigateByStep,
    cancelPendingBatchLoad,
    requestStopResultFilterSearch,
  });

  if (!activeTab) {
    return null;
  }

  return (
    <>
      <SearchSidebarChrome {...searchSidebarChromeProps}>
        <SearchSidebarBody {...searchSidebarBodyProps} />
      </SearchSidebarChrome>

      <SearchPanelOverlays {...searchPanelOverlaysProps} />
    </>
  );
}
