import {
  startTransition,
  useMemo,
  useRef,
} from 'react';
import type { FilterRulesEditorProps } from '@/components/search-panel/FilterRulesEditor';
import {
  SearchSidebarBody,
  SearchPanelOverlays,
  SearchSidebarChrome,
  useFilterRules,
  useSearchPanelChrome,
  useSearchPanelInputSupport,
  useSearchKeywordKeyDown,
  useSearchMatchNavigation,
  useSearchPanelDerivedState,
  useSearchPanelLocalState,
  useSearchPanelUiState,
  useSearchPanelRuntimeRefs,
  useSearchPanelSnapshotPersistence,
  useSearchApplyResultFilter,
  useSearchResultFilterStepNavigation,
  useSearchStepNavigation,
  useSearchReplaceHandlers,
  useSearchFirstMatchSearch,
  useSearchPanelRestoreEffect,
  useSearchPanelResetState,
  useSearchBatchControl,
  useSearchQueryOptions,
  useSearchQuerySectionProps,
  useSearchResultPanel,
  useSearchSessionLifecycle,
  useSearchPanelLoadMoreHandlers,
  useSearchPanelRunHandlers,
  useSearchSidebarFrame,
  useSearchPanelStoreState,
} from '@/components/search-panel';
export function SearchReplacePanel() {
  const {
    activeCursorPosition,
    activeTab,
    activeTabId,
    fontFamily,
    fontSize,
    language,
    recentReplaceValues,
    recentSearchKeywords,
    setCursorPosition,
    updateSettings,
    updateTab,
  } = useSearchPanelStoreState();

  const {
    appliedResultFilterKeyword,
    caseSensitive,
    currentFilterMatchIndex,
    currentMatchIndex,
    errorMessage,
    feedbackMessage,
    filterMatches,
    filterRuleGroups,
    isOpen,
    isResultFilterSearching,
    isSearching,
    keyword,
    matches,
    panelMode,
    parseEscapeSequences,
    replaceValue,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultPanelHeight,
    resultPanelState,
    reverseSearch,
    searchMode,
    searchSidebarWidth,
    setAppliedResultFilterKeyword,
    setCaseSensitive,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterRuleGroups,
    setIsOpen,
    setIsResultFilterSearching,
    setIsSearching,
    setKeyword,
    setMatches,
    setPanelMode,
    setParseEscapeSequences,
    setReplaceValue,
    setResultFilterKeyword,
    setResultFilterStepLoadingDirection,
    setResultPanelHeight,
    setResultPanelState,
    setReverseSearch,
    setSearchMode,
    setSearchSidebarWidth,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
  } = useSearchPanelLocalState();

  const {
    inputContextCopyLabel,
    inputContextCutLabel,
    inputContextPasteLabel,
    isFilterMode,
    isReplaceMode,
    messages,
    normalizedFilterRuleGroups,
    resultListTextStyle,
  } = useSearchPanelUiState({
    filterRuleGroups,
    fontFamily,
    fontSize,
    language,
    panelMode,
  });
  const {
    getSearchSidebarOccludedRightPx,
    handleSearchUiBlurCapture,
    handleSearchUiFocusCapture,
    handleSearchUiPointerDownCapture,
    isSearchSidebarResizing,
    isSearchUiActive,
    searchSidebarContainerRef,
    startSearchSidebarResize,
  } = useSearchSidebarFrame({
    isOpen,
    searchSidebarWidth,
    setSearchSidebarWidth,
  });

  const {
    cachedFilterRef,
    cachedSearchRef,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    filterCountCacheRef,
    filterLineCursorRef,
    filterRunVersionRef,
    filterSessionIdRef,
    loadMoreDebounceRef,
    loadMoreLockRef,
    loadMoreSessionRef,
    minimizedResultWrapperRef,
    previousActiveTabIdRef,
    resultFilterStepRunVersionRef,
    resultListRef,
    resultPanelWrapperRef,
    runVersionRef,
    searchInputRef,
    searchSessionIdRef,
    sessionRestoreRunVersionRef,
    stopResultFilterSearchRef,
    tabSearchPanelStateRef,
  } = useSearchPanelRuntimeRefs();

  const {
    focusSearchInput,
    handleInputContextMenuAction,
    handleSearchSidebarContextMenu,
    inputContextMenu,
    inputContextMenuRef,
    rememberReplaceValue,
    rememberSearchKeyword,
  } = useSearchPanelInputSupport({
    isOpen,
    recentReplaceValues,
    recentSearchKeywords,
    searchInputRef,
    updateSettings,
  });

  const { cancelPendingBatchLoad, requestStopResultFilterSearch } = useSearchBatchControl({
    filterRunVersionRef,
    loadMoreDebounceRef,
    loadMoreLockRef,
    loadMoreSessionRef,
    resultFilterStepRunVersionRef,
    runVersionRef,
    setIsSearching,
    setResultFilterStepLoadingDirection,
    stopResultFilterSearchRef,
  });

  const { setFilterSessionId, setSearchSessionId } = useSearchSessionLifecycle({
    filterSessionIdRef,
    searchSessionIdRef,
  });

  const { resetFilterState, resetSearchState } = useSearchPanelResetState({
    cachedFilterRef,
    cachedSearchRef,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndex,
    currentFilterMatchIndexRef,
    currentMatchIndex,
    currentMatchIndexRef,
    filterCountCacheRef,
    filterLineCursorRef,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setFilterMatches,
    setFilterSessionId,
    setMatches,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
  });

  const {
    addFilterRule,
    clearFilterRules,
    effectiveFilterRules,
    filterGroupNameInput,
    filterRuleDragState,
    filterRules,
    filterRulesKey,
    filterRulesPayload,
    handleDeleteFilterRuleGroup,
    handleExportFilterRuleGroups,
    handleImportFilterRuleGroups,
    handleLoadFilterRuleGroup,
    handleSaveFilterRuleGroup,
    handleSelectedFilterGroupChange,
    hasAnyConfiguredFilterRule,
    moveFilterRule,
    onFilterRuleDragEnd,
    onFilterRuleDragOver,
    onFilterRuleDragStart,
    onFilterRuleDrop,
    removeFilterRule,
    selectedFilterGroupName,
    setFilterGroupNameInput,
    updateFilterRule,
  } = useFilterRules({
    messages,
    normalizedFilterRuleGroups,
    resetFilterState,
    setErrorMessage,
    setFeedbackMessage,
    setFilterRuleGroups,
  });

  const {
    backendResultFilterKeyword,
    effectiveSearchKeyword,
    isResultFilterActive,
    visibleCurrentFilterMatchIndex,
    visibleCurrentMatchIndex,
    visibleFilterMatches,
    visibleMatches,
  } = useSearchPanelDerivedState({
    appliedResultFilterKeyword,
    caseSensitive,
    currentFilterMatchIndex,
    currentMatchIndex,
    filterMatches,
    keyword,
    matches,
    parseEscapeSequences,
  });

  const { executeFilter, executeSearch } = useSearchPanelRunHandlers({
    activeTabId,
    backendResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    cancelPendingBatchLoad,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    effectiveSearchKeyword,
    filterCountCacheRef,
    filterFailedLabel: messages.filterFailed,
    filterLineCursorRef,
    filterRulesKey,
    filterRulesPayload,
    filterRunVersionRef,
    isFilterMode,
    keyword,
    parseEscapeSequences,
    resetFilterState,
    resetSearchState,
    runVersionRef,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsSearching,
    setMatches,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
  });

  const {
    loadMoreMatches,
    loadMoreFilterMatches,
  } = useSearchPanelLoadMoreHandlers({
    activeTabId,
    backendResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    effectiveSearchKeyword,
    filterFailedLabel: messages.filterFailed,
    filterLineCursorRef,
    filterRulesKey,
    filterRulesPayload,
    filterSessionIdRef,
    isFilterMode,
    loadMoreLockRef,
    loadMoreSessionRef,
    parseEscapeSequences,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    searchSessionIdRef,
    setErrorMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsSearching,
    setMatches,
    setSearchSessionId,
    startTransition,
  });

  const executeFirstMatchSearch = useSearchFirstMatchSearch({
    activeTabId: activeTab?.id ?? null,
    backendResultFilterKeyword,
    cachedSearchRef,
    cancelPendingBatchLoad,
    caseSensitive,
    chunkCursorRef,
    effectiveSearchKeyword,
    executeSearch,
    isFilterMode,
    keyword,
    parseEscapeSequences,
    resetSearchState,
    runVersionRef,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setCurrentMatchIndex,
    setErrorMessage,
    setIsSearching,
    setMatches,
    setSearchSessionId,
    startTransition,
  });

  const {
    handleSelectMatch,
    navigateToFilterMatch,
    navigateToMatch,
  } = useSearchMatchNavigation({
    activeTabId: activeTab?.id ?? null,
    filterMatches,
    getSearchSidebarOccludedRightPx,
    isFilterMode,
    matches,
    setCursorPosition,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setFeedbackMessage,
  });

  const hasMoreMatches = chunkCursorRef.current !== null;
  const hasMoreFilterMatches = filterLineCursorRef.current !== null;

  const navigateByStep = useSearchStepNavigation({
    activeCursorPosition,
    activeTabId: activeTab?.id ?? null,
    backendResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    executeFilter,
    executeFirstMatchSearch,
    filterCountCacheRef,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterRulesPayload,
    filterFailedLabel: messages.filterFailed,
    isFilterMode,
    keyword,
    loadMoreFilterMatches,
    loadMoreLockRef,
    loadMoreMatches,
    matches,
    navigateToFilterMatch,
    navigateToMatch,
    nextMatchLabel: messages.nextMatch,
    prevMatchLabel: messages.prevMatch,
    rememberSearchKeyword,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setMatches,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    startTransition,
  });

  const { handleReplaceAll, handleReplaceCurrent } = useSearchReplaceHandlers({
    activeTabId: activeTab?.id ?? null,
    activeTabLineCount: activeTab?.lineCount ?? null,
    backendResultFilterKeyword,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    executeSearch,
    keyword,
    navigateToMatch,
    noReplaceMatchesMessage: messages.noReplaceMatches,
    parseEscapeSequences,
    rememberReplaceValue,
    rememberSearchKeyword,
    replaceAllFailedLabel: messages.replaceAllFailed,
    replaceCurrentFeedback: messages.replacedCurrent,
    replaceFailedLabel: messages.replaceFailed,
    replacedAllFeedback: messages.replacedAll,
    replaceValue,
    searchMode,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setMatches,
    setSearchSessionId,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
    updateTab,
  });

  const handleKeywordKeyDown = useSearchKeywordKeyDown({
    executeFilter,
    executeSearch,
    isFilterMode,
    isSearching,
    keyword,
    navigateByStep,
    rememberSearchKeyword,
    reverseSearch,
    searchInputRef,
    setIsOpen,
    setResultPanelState,
  });


  useSearchPanelRestoreEffect({
    activeTabId: activeTab?.id ?? null,
    cachedFilterRef,
    cachedSearchRef,
    chunkCursorRef,
    countCacheRef,
    filterCountCacheRef,
    filterLineCursorRef,
    filterRulesKey,
    filterRulesPayload,
    previousActiveTabIdRef,
    resetFilterState,
    resetSearchState,
    sessionRestoreRunVersionRef,
    setAppliedResultFilterKeyword,
    setCaseSensitive,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsOpen,
    setIsResultFilterSearching,
    setKeyword,
    setMatches,
    setPanelMode,
    setParseEscapeSequences,
    setReplaceValue,
    setResultFilterKeyword,
    setResultPanelHeight,
    setResultPanelState,
    setReverseSearch,
    setSearchMode,
    setSearchSessionId,
    setSearchSidebarWidth,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    stopResultFilterSearchRef,
    tabSearchPanelStateRef,
  });

  useSearchPanelSnapshotPersistence({
    activeTabId,
    appliedResultFilterKeyword,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    currentFilterMatchIndex,
    currentMatchIndex,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterSessionIdRef,
    isOpen,
    keyword,
    matches,
    panelMode,
    parseEscapeSequences,
    replaceValue,
    resultFilterKeyword,
    resultPanelHeight,
    resultPanelState,
    reverseSearch,
    searchMode,
    searchSessionIdRef,
    searchSidebarWidth,
    tabSearchPanelStateRef,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
  });

  const handleApplyResultFilter = useSearchApplyResultFilter({
    appliedResultFilterKeyword,
    cancelPendingBatchLoad,
    caseSensitive,
    executeFilter,
    executeSearch,
    isFilterMode,
    isResultFilterSearching,
    keyword,
    requestStopResultFilterSearch,
    resultFilterKeyword,
    setAppliedResultFilterKeyword,
    setIsResultFilterSearching,
    stopResultFilterSearchRef,
  });

  const navigateResultFilterByStepRef = useRef<((step: number) => Promise<void>) | null>(null);

  const {
    copyPlainTextResultEntries,
    copyPlainTextResults,
    displayTotalFilterMatchedLineCount,
    displayTotalFilterMatchedLineCountText,
    displayTotalMatchCount,
    displayTotalMatchCountText,
    displayTotalMatchedLineCountText,
    filterToggleLabel,
    handleClearResultFilter,
    handleCloseResultPanel,
    handleRefreshResults,
    handleReopenResultPanel,
    handleResultFilterAction,
    handleResultFilterNext,
    handleResultFilterPrev,
    handleResultListScroll,
    handleResultPanelResizeMouseDown,
    hasAppliedResultFilterKeyword,
    plainTextResultEntries,
    resultToggleTitle,
    scrollResultItemIntoView,
    toggleResultPanelAndRefresh,
  } = useSearchResultPanel({
    cancelPendingBatchLoad,
    executeFilter,
    executeSearch,
    filterMatchesLength: filterMatches.length,
    filterRulesPayloadLength: filterRulesPayload.length,
    hasMoreFilterMatches,
    hasMoreMatches,
    isFilterMode,
    isOpen,
    isResultFilterSearching,
    isSearching,
    keyword,
    loadMoreDebounceRef,
    loadMoreFilterMatches,
    loadMoreLockRef,
    loadMoreMatches,
    matchesLength: matches.length,
    messages,
    navigateResultFilterByStepRef,
    onApplyResultFilter: handleApplyResultFilter,
    rememberSearchKeyword,
    requestStopResultFilterSearch,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultListRef,
    resultPanelHeight,
    resultPanelState,
    setAppliedResultFilterKeyword,
    setErrorMessage,
    setFeedbackMessage,
    setResultFilterKeyword,
    setResultPanelHeight,
    setResultPanelState,
    totalFilterMatchedLineCount,
    totalMatchCount,
    totalMatchedLineCount,
    visibleFilterMatches,
    visibleMatches,
  });

  const navigateResultFilterByStep = useSearchResultFilterStepNavigation({
    activeTabId: activeTab?.id ?? null,
    cachedFilterRef,
    cachedSearchRef,
    caseSensitive,
    chunkCursorRef,
    countCacheRef,
    currentFilterMatchIndexRef,
    currentMatchIndexRef,
    effectiveSearchKeyword,
    filterCountCacheRef,
    filterLineCursorRef,
    filterMatches,
    filterRulesKey,
    filterRulesPayload,
    isFilterMode,
    isResultFilterSearching,
    isSearching,
    keyword,
    loadMoreLockRef,
    matches,
    parseEscapeSequences,
    resultFilterKeyword,
    resultFilterStepNoMatch: messages.resultFilterStepNoMatch,
    resultFilterStepRunVersionRef,
    scrollResultItemIntoView,
    searchFailedLabel: messages.searchFailed,
    searchMode,
    setCurrentFilterMatchIndex,
    setCurrentMatchIndex,
    setErrorMessage,
    setFeedbackMessage,
    setFilterMatches,
    setFilterSessionId,
    setIsSearching,
    setMatches,
    setResultFilterStepLoadingDirection,
    setSearchSessionId,
    setTotalFilterMatchedLineCount,
    setTotalMatchCount,
    setTotalMatchedLineCount,
    startTransition,
  });

  navigateResultFilterByStepRef.current = navigateResultFilterByStep;

  const filterRulesEditorProps = useMemo<FilterRulesEditorProps>(
    () => ({
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      hasAnyConfiguredFilterRule,
      messages,
      normalizedFilterRuleGroups,
      selectedFilterGroupName,
      onAddFilterRule: addFilterRule,
      onClearFilterGroupNameInput: () => setFilterGroupNameInput(''),
      onClearFilterRules: clearFilterRules,
      onDeleteFilterRuleGroup: () => void handleDeleteFilterRuleGroup(),
      onExportFilterRuleGroups: () => void handleExportFilterRuleGroups(),
      onFilterGroupNameInputChange: setFilterGroupNameInput,
      onImportFilterRuleGroups: () => void handleImportFilterRuleGroups(),
      onKeywordKeyDown: handleKeywordKeyDown,
      onLoadFilterRuleGroup: handleLoadFilterRuleGroup,
      onMoveFilterRule: moveFilterRule,
      onRemoveFilterRule: removeFilterRule,
      onRuleDragEnd: onFilterRuleDragEnd,
      onRuleDragOver: onFilterRuleDragOver,
      onRuleDragStart: onFilterRuleDragStart,
      onRuleDrop: onFilterRuleDrop,
      onSaveFilterRuleGroup: () => void handleSaveFilterRuleGroup(),
      onSelectedFilterGroupChange: handleSelectedFilterGroupChange,
      onToggleResultPanelAndRefresh: toggleResultPanelAndRefresh,
      onUpdateFilterRule: updateFilterRule,
    }),
    [
      addFilterRule,
      clearFilterRules,
      effectiveFilterRules,
      filterGroupNameInput,
      filterRuleDragState,
      filterRules,
      filterToggleLabel,
      handleDeleteFilterRuleGroup,
      handleExportFilterRuleGroups,
      handleImportFilterRuleGroups,
      handleKeywordKeyDown,
      handleLoadFilterRuleGroup,
      handleSaveFilterRuleGroup,
      handleSelectedFilterGroupChange,
      hasAnyConfiguredFilterRule,
      messages,
      moveFilterRule,
      normalizedFilterRuleGroups,
      onFilterRuleDragEnd,
      onFilterRuleDragOver,
      onFilterRuleDragStart,
      onFilterRuleDrop,
      removeFilterRule,
      selectedFilterGroupName,
      setFilterGroupNameInput,
      toggleResultPanelAndRefresh,
      updateFilterRule,
    ]
  );

  const searchQueryOptions = useSearchQueryOptions({
    caseSensitive,
    handleKeywordKeyDown,
    handleReplaceAll,
    handleReplaceCurrent,
    isReplaceMode,
    keyword,
    messages,
    navigateByStep,
    parseEscapeSequences,
    recentReplaceValues,
    recentSearchKeywords,
    replaceValue,
    resetSearchState,
    resultToggleTitle,
    reverseSearch,
    searchInputRef,
    searchMode,
    setCaseSensitive,
    setErrorMessage,
    setFeedbackMessage,
    setKeyword,
    setParseEscapeSequences,
    setReplaceValue,
    setReverseSearch,
    setSearchMode,
    toggleResultPanelAndRefresh,
  });

  const searchQuerySectionProps = useSearchQuerySectionProps({
    canReplace: !!activeTab,
    ...searchQueryOptions,
  });

  const {
    searchPanelOverlaysProps,
    searchSidebarBodyProps,
    searchSidebarChromeProps,
  } = useSearchPanelChrome({
    handleSearchUiBlurCapture,
    handleSearchUiFocusCapture,
    handleSearchUiPointerDownCapture,
    isSearchSidebarResizing,
    isSearchUiActive,
    searchSidebarContainerRef,
    startSearchSidebarResize,
    activeTabId,
    currentFilterMatchIndex,
    currentMatchIndex,
    effectiveFilterRulesLength: effectiveFilterRules.length,
    errorMessage,
    feedbackMessage,
    filterMatches,
    filterRulesPayloadLength: filterRulesPayload.length,
    fontFamily,
    hasActiveTab: !!activeTab,
    hasMoreFilterMatches,
    hasMoreMatches,
    isFilterMode,
    isOpen,
    isResultFilterActive,
    isResultFilterSearching,
    isSearching,
    keyword,
    matches,
    messages,
    minimizedResultWrapperRef,
    panelMode,
    previousActiveTabIdRef,
    resultFilterKeyword,
    resultFilterStepLoadingDirection,
    resultListRef,
    resultListTextStyle,
    resultPanelHeight,
    resultPanelState,
    resultPanelWrapperRef,
    reverseSearch,
    searchSidebarWidth,
    stopResultFilterSearchRef,
    visibleCurrentFilterMatchIndex,
    visibleCurrentMatchIndex,
    visibleFilterMatches,
    visibleMatches,
    setAppliedResultFilterKeyword,
    setErrorMessage,
    setFeedbackMessage,
    setIsOpen,
    setIsResultFilterSearching,
    setPanelMode,
    setResultFilterKeyword,
    setResultPanelState,
    filterRulesEditorProps,
    searchQuerySectionProps,
    focusSearchInput,
    handleInputContextMenuAction,
    handleSearchSidebarContextMenu,
    inputContextCopyLabel,
    inputContextCutLabel,
    inputContextMenu,
    inputContextMenuRef,
    inputContextPasteLabel,
    copyPlainTextResultEntries,
    copyPlainTextResults,
    displayTotalFilterMatchedLineCount,
    displayTotalFilterMatchedLineCountText,
    displayTotalMatchCount,
    displayTotalMatchCountText,
    displayTotalMatchedLineCountText,
    handleClearResultFilter,
    handleCloseResultPanel,
    handleRefreshResults,
    handleReopenResultPanel,
    handleResultFilterAction,
    handleResultFilterNext,
    handleResultFilterPrev,
    handleResultListScroll,
    handleResultPanelResizeMouseDown,
    hasAppliedResultFilterKeyword,
    plainTextResultEntryCount: plainTextResultEntries.length,
    handleSelectMatch,
    navigateByStep,
    cancelPendingBatchLoad,
    requestStopResultFilterSearch,
  });

  if (!activeTab) {
    return null;
  }

  return (
    <>
      <SearchSidebarChrome {...searchSidebarChromeProps}>
        <SearchSidebarBody {...searchSidebarBodyProps} />
      </SearchSidebarChrome>

      <SearchPanelOverlays {...searchPanelOverlaysProps} />
    </>
  );
}
